## Lenta parser metric refactoring
microservices-course-itmo/lenta-parser-service pull request #30
Opened 2021-03-10 15:34 UTC by kosch71

- Renaming metrics
- Use System.nanoTime() instead of Date

2021-03-11 13:15 UTC, MaximKuznetsov17 requested changes

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/controller/LentaStoreController.java
> +        ParserRspImpl parserRsp = parserReqServiceImpl.getJson(new Date().getHours() * 60 + new Date().getMinutes());
Может эту логику лучше вынсти в переменную? Просто не совсем удобно читать это

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/cron/ExportProductDtoList.java
> +                    .parseWineList(requestsService.getJson(new Date().getHours() * 60 + new Date().getMinutes()))
Аналогично

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/parser/impl/ParserReqServiceImpl.java
> +                }
Скобочка вылезла
Чаще нажимайте `ctrl + alt + L`

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/parser/impl/ParserReqServiceImpl.java
> +                if (i < tempBatchSize || i >= tempBatchSize + 6) {
Что значит 6? Если это какая-то константа со смыслом, то такое следует выносить в константы

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/parser/impl/ParserReqServiceImpl.java
> +                if (wineList.getJsonList().size() % 8 == 0) {
Какой смысл у 8? Также в константы нужно вынести, чтобы было понятнее
Вероятно, через месяц вы уже можете не вспомнить что это значило
Особенно, если с кодом будет работать человек, который его не писал

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/parser/impl/ParserReqServiceImpl.java
> +        if (wineList.getJsonList().size() % 8 != 0){
Аналогично

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/parser/impl/ParserReqServiceImpl.java
> +            Document iterdoc;
Странное название, но ладно

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/lenta/service/parser/impl/ParserReqServiceImpl.java
> +                    jsonString.put("wineCapacity", value.text().replace(" L", ""));
А если вдруг `wineCapacity == null`? Тут не может быть NullPointerException?

2021-03-11 13:15 UTC, MaximKuznetsov17 commented on src/main/resources/application.properties
> +cron.expression=0 * * * * *
Что-то здесь у вас не то
Во-первых, не совпадает с комментарием выше, а во-вторых, судя по expression, джоба будет стартовать каждую минуту
Вам это и надо?

2021-03-11 13:22 UTC, O-o-l-e-g commented on src/main/resources/application.properties
> +cron.expression=0 * * * * *
да

2021-03-11 13:23 UTC, MaximKuznetsov17 commented on src/main/resources/application.properties
> +cron.expression=0 * * * * *
Тогда стоит комментарий подправить

2021-03-11 13:47 UTC, HappyLiner requested changes

2021-03-11 13:47 UTC, HappyLiner commented on src/main/java/com/wine/to/up/lenta/service/helpers/ExportProductDtoListHelper.java
> +    }
1) Методы самописного билдера должны возвращать объект класса *Builder, а не быть процедурами, чтобы можно было писать `builder.fillNewPrice(wine.getNewPrice()).fillTitle(wine.getTitle()).fillRating(wine.getRating())`.
2) Для таких условий лучше использовать тернарный оператор.

2021-03-11 14:18 UTC, closed without merging

2021-03-18 17:16 UTC, InRedikaWB commented
@O-o-l-e-g  @kosch71 а какова судьба этого реквеста? А то я вижу, что его поревьювили и... просто закрыли? Как-то не хорошо получается.

2021-03-24 17:54 UTC, O-o-l-e-g commented on src/main/java/com/wine/to/up/lenta/service/helpers/ExportProductDtoListHelper.java
> +    }
Это не самописный билдер, это метод проверки на null значения, который в случае, когда значение не null вызывает ParserApi.Wine.newBuilder();

2021-03-24 18:27 UTC, HappyLiner commented on src/main/java/com/wine/to/up/lenta/service/helpers/ExportProductDtoListHelper.java
> +    }
Этот комментарий был адресован всему классу, не только этому методу. Перефразирую
Весь этот класс лучше переписать по принципу билдера, чтобы эти методы возвращали `ParserApi.Wine.Builder` , а внутри достаточно написать `return wine.getNewPrice() != null ? builder.setNewPrice(wine.getNewPrice()) : builder`